name: soap-kg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas>=2.0.0
  - numpy>=1.24.0
  - networkx>=3.0
  - matplotlib>=3.6.0
  - seaborn>=0.12.0
  - requests>=2.28.0
  - tqdm>=4.65.0
  - scikit-learn>=1.3.0
  - spacy>=3.6.0
  - plotly>=5.15.0
  - jupyter
  - ipykernel
  - pip
  - pip:
    - python-dotenv>=1.0.0
    - openai>=1.0.0